uptown_hound/urls.py
# ===============================================
# uptown_hound/urls.py
# ===============================================


from django.contrib import admin
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from shop import views


urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^cart/remove/$', views.cart_remove, name='cart_remove'),
    url(r'^category/search/$', views.search, name='search'),
    url(r'^category/(?P<category_path>.+)/$', views.category, name='category'),
    url(r'^checkout/thankyou/(?P<invoice_number>[\w-]+)/$',
        views.confirm_order),
    url(r'^checkout/$', views.OrderWizard.as_view(), name='checkout'),
    url(r'^order-status/$', views.order_status, name='order_status'),
    url(r'^product/(?P<product_slug>[\w-]+)/$', views.product, name='product'),
    url(r'^store/contact/$',
        TemplateView.as_view(template_name='store/contact.html')),
    url(r'^store/privacy/$',
        TemplateView.as_view(template_name='store/privacy.html')),
    url(r'^store/shipping-returns/$',
        TemplateView.as_view(template_name='store/ship_returns.html')),
    url(r'^store/terms/$',
        TemplateView.as_view(template_name='store/terms.html')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.error404
handler500 = views.error500

shop/models.py
# ===============================================
# shop/models.py
# ===============================================

from decimal import Decimal

from django.db import models

from django_countries.fields import CountryField

from shop.constants import ORDER_STATUS_CHOICES


class Order(models.Model):
    """
    Customer order; created after successful payment
    """
    customer_name = models.CharField(max_length=128, verbose_name='Name')
    customer_street = models.CharField(
        max_length=256, verbose_name='Street Address'
    )
    customer_city = models.CharField(max_length=128, verbose_name='City')
    customer_state = models.CharField(
        max_length=128, verbose_name='State/Province'
    )
    customer_nation = CountryField(verbose_name='Country', blank_label='')
    customer_postal = models.CharField(
        max_length=64, verbose_name='Zip/Postal Code'
    )
    customer_email = models.EmailField(max_length=254, verbose_name='Email')
    customer_phone = models.CharField(
        max_length=32, verbose_name='Phone', blank=True, null=True
    )
    customer_comments = models.TextField(
        verbose_name='Order comments', blank=True, null=True
    )

    time = models.DateTimeField(auto_now_add=True, null=True)
    item_total = models.DecimalField(
        max_digits=6, decimal_places=2, verbose_name='Item Total',
        default=Decimal('0.00')
    )
    shipping_total = models.DecimalField(
        max_digits=6, decimal_places=2, verbose_name='Shipping Total',
        default=Decimal('0.00')
    )
    order_total = models.DecimalField(
        max_digits=6, decimal_places=2, verbose_name='Order Total',
        default=Decimal('0.00')
    )

    status = models.CharField(
        max_length=32, choices=ORDER_STATUS_CHOICES, default='Processing'
    )
    shipment_time = models.DateTimeField(blank=True, null=True)
    shipment_method = models.CharField(max_length=128, blank=True, null=True)
    shipment_tracking = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return str(self.id)


class OrderItem(models.Model):
    """
    Size/price variation for a Product in an Order
    """
    order = models.ForeignKey(Order)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    product = models.ForeignKey('Product', blank=True, null=True)
    quantity = models.IntegerField()
    size = models.CharField(max_length=64, blank=True, null=True)
    sku = models.CharField(max_length=32, blank=True, null=True)
    width = models.CharField(max_length=64, blank=True, null=True)


class Product(models.Model):
    """
    Product sold in the shop; set active to False for out of stock items
    """
    active = models.BooleanField(default=True)
    category = models.ManyToManyField('ProdCategory', blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    main_img = models.ForeignKey(
        'ProdImage', on_delete=models.SET_NULL, blank=True, null=True
    )
    name = models.CharField(max_length=64)
    related_products = models.ManyToManyField('self', blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)

    def __str__(self):
        return self.name

    def first_child(self):
        """
        Find leaf in the product category tree path. Assume that next() will
        return a leaf category, but arbitrarily return one of the parent
        categories by default just in case
        """
        child = next((
                category for category in self.category.all()
                if not category.is_parent()
            ),
            self.category.all().first()
        )
        return child

    def price_range(self):
        """
        Generate a low to high price range based on ProdVariations for
        use in templates
        """
        variations = ProdVariation.objects.filter(
            product=self
        ).order_by('price')
        min_price = variations.first().price
        max_price = variations.last().price

        # Return a formatted range when the variations have different prices
        if min_price != max_price:
            return '${:.2f}'.format(min_price) + ' - {:.2f}'.format(max_price)

        # Return the formatted minimum when variations are all the same price
        return '${:.2f}'.format(min_price)

    def thumbnail(self):
        """
        Create a thumbnail of the Product's main image for use in the admin
        """
        return '<img src="%s" width="100" />' % (self.main_img.image.url)

    thumbnail.allow_tags = True


class ProdCategory(models.Model):
    """
    Hierarchical categories for organizing Products
    """
    name = models.CharField(max_length=32)
    parent = models.ForeignKey(
        'self', related_name='children', blank=True, null=True
    )
    slug = models.SlugField()

    class Meta:
        verbose_name_plural = 'product categories'

    def __str__(self):
        """
        Override to include parent for displaying in admin
        """
        return (
            self.name +
            (' ({0})'.format(self.parent.name) if self.parent else '')
        )

    def is_parent(self):
        """
        Returns boolean value for whether a category has a child
        """
        return ProdCategory.objects.filter(parent=self).exists()

    def path(self):
        """
        Generates a full URL path for a category that includes all
        parent categories
        """
        slugs, child = [self.slug], True

        while child:
            if self.parent:
                slugs.append(self.parent.slug)
                self = self.parent
            else:
                # End the loop when the leaf is hit
                child = False

        return '/'.join(slugs[::-1]) + '/'


class ProdImage(models.Model):
    """
    Photo for a Product
    """
    subject = models.ForeignKey('Product')
    tag = models.CharField(max_length=10)
    image = models.FileField(upload_to='products/')

    def __str__(self):
        return self.subject.name + ' ' + self.tag

    def thumbnail(self):
        """
        Creates image thumbnail for use in the admin
        """
        return '<img src="%s" width="100" />' % (self.image.url)
    thumbnail.allow_tags = True


class ProdVariation(models.Model):
    """
    Size/price variation for a Product
    """
    price = models.DecimalField(max_digits=6, decimal_places=2)
    product = models.ForeignKey(
        'Product', related_name='variations', blank=True, null=True
    )
    size = models.CharField(max_length=64, blank=True, null=True)
    sku = models.CharField(max_length=32, blank=True, null=True)
    sort_order = models.IntegerField(default=0, blank=True, null=True)
    width = models.CharField(max_length=64, blank=True, null=True)

templates/cart.html
{% extends 'base.html' %}

{% block page_title %}
    Shopping Bag - 
{% endblock %}

{% block content %}

    <div class="container-fluid page-title text-center">
        Shopping Bag
    </div>

    <div class="container cart-wrapper js-cart-empty {% if request.session.cart.items|length > 0 %} hidden {% endif %}">
        <div class="row margin-top-lg">
            <div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 message-block">
                Your shopping bag is currently empty.
            </div>
        </div>
    </div>

    {% if request.session.cart.items|length > 0 %}

        <div class="container margin-top-lg js-cart-full">
            <form method="post">    
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        {% csrf_token %}
                        <table class="table cart-table">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th class="thumb-col hidden-xs"></td>
                                    <th>Item</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                {{ formset.management_form }}
                                {% for form in formset %}
                                    <tr data-sku="{{ form.initial.sku }}">
                                        <td>
                                            <a href="/cart/remove/?id={{ form.initial.sku }}" class="js-remove-item" data-sku="{{ form.initial.sku }}">
                                                <span class="glyphicon glyphicon-remove-circle"></span>
                                            </a>
                                        </td>
                                        <td class="thumb-col hidden-xs">
                                            <a href="/product/{{ form.initial.url }}/">
                                                <img src="{{ form.initial.image }}" class="img-responsive">
                                            </a>
                                        </td>
                                        <td class="detail-col">
                                            <a href="/product/{{ form.initial.url }}/">{{ form.initial.product }}</a>
                                            <br/>{{ form.initial.size }}
                                            <br/>${{ form.initial.price|floatformat:2 }}
                                        </td>
                                        <td>
                                            {{ form.sku }}
                                            {{ form.quantity }}
                                        </td>
                                        <td class="price-col">
                                            ${{ form.initial.line_total|floatformat:2 }}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-6 col-xs-offset-6 col-sm-4 col-sm-offset-8 col-md-3 col-md-offset-9 col-lg-3 col-lg-offset-9 text-right">
                        <button type="submit" class="btn btn-default form-control button-light">Update Bag</button>
                    </div>
                </div>
            </form>
            <div class="row">
                <div class="col-xs-12 col-xs-offset-0 col-sm-7 col-sm-offset-5 col-md-6 col-md-offset-6 col-lg-5 col-lg-offset-7">
                    {% include 'includes/totals.html' with button_url='/checkout/' button_text='Checkout' shipping_calc=True %}
                </div>
            </div>
        </div>

        <!-- Modal for selecting country to calculate shipping -->
        <div class="modal fade shipping-calc-modal" tabindex="-1" role="dialog" aria-labelledby="shippingCalcModal" aria-hidden="true">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Select shipping country...</h4>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="modal-body">
                            <div class="form-group">
                                {{ country_form.country }}
                            </div>
                        </div>
                        <div class="modal-footer">
                            <input type="submit" class="btn btn-default button-dark" value="Calculate Shipping"></input>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}


{% endblock %}

templates/category.html
{% extends 'base.html' %}

{% block page_title %}
    {{ category.name }} - 
{% endblock %}

{% block content %}
    
    <div class="container-fluid page-title text-center">
        {{ category.name }}
    </div>

    {% include 'includes/breadcrumbs.html' %}
    
    <div class="container">
        <div class="row">
            {% for product in products %}
                <div class="col-xs-6 col-sm-4 col-md-3 col-lg-3 product-thumb">
                    <a href="/product/{{ product.slug }}/">
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <img src="{{ product.main_img.image.url }}" class="img-responsive">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-11 col-xs-offset-1 col-sm-11 col-sm-offset-1 col-md-11 col-md-offset-1 col-lg-10 col-lg-offset-1 product-name">{{ product.name }}</div>
                        </div>
                        <div class="row">
                            <div class="col-xs-11 col-xs-offset-1 col-sm-11 col-sm-offset-1 col-md-11 col-md-offset-1 col-lg-10 col-lg-offset-1 price">{{ product.price_range }}</div>
                        </div>
                    </a>
                </div>
                {% if forloop.counter|divisibleby:2 %}
                    <!-- Clear to fix wrapping row with uneven heights in mobile view -->
                    <div class="clearfix hidden-sm hidden-md hidden-lg"></div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}

    <div class="container-fluid page-title text-center">
        Checkout / {{ wizard.steps.current }}
    </div>

    <div class="container checkout-wrapper">
        <div class="row checkout-nav-row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                {% if wizard.steps.current != wizard.steps.first %}
                    <form method="post">
                        {% csrf_token %}
                        <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}" class="btn button-light">
                            <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;&nbsp;Back to Shipping
                        </button>
                    </form>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <form method="post" class="js-checkout-{{ wizard.steps.current }}" autocomplete="on">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                    {% block checkout_form %}
                    {% endblock %}
                </div>
                <div class="col-xs-12 col-xs-offset-0 col-sm-5 col-sm-offset-1 col-md-5 col-md-offset-1 col-lg-5 col-lg-offset-1">
                    {% if shipping_info.customer_nation and wizard.steps.current != wizard.steps.first %}
                        <div class="row h3">
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                Shipping Details
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right item-details">
                                {{ shipping_info.customer_name }}<br/>
                                {{ shipping_info.customer_street }}<br/>
                                {{ shipping_info.customer_city }}, {{ shipping_info.customer_state }} 
                                {{ shipping_info.customer_nation }} {{ shipping_info.customer_postal }}<br/>
                                {{ shipping_info.customer_email }}
                            </div>
                        </div>
                    {% endif %}
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 h3">
                            Your Order 
                        </div>
                    </div>
                    {% for item in request.session.cart.items %}
                        <div class="row detail-col">
                            <div class="col-xs-7 col-sm-8 col-md-6 col-lg-6">
                                {{ item.product }}<br/>
                                {{ item.size}}
                            </div>
                            <div class="col-xs-5 col-sm-4 col-md-6 col-lg-6 text-right">
                                {{ item.quantity }} x ${{ item.price|floatformat:2 }} = ${{ item.line_total|floatformat:2 }}
                            </div>
                        </div>
                    {% endfor %}
                    {% include 'includes/totals.html' with button_type='form' button_text=button_text %}
                </div>
            </form>
        </div>
    </div>

{% endblock %}

{% block extra_js %}

    <!-- Custom JS for checkout/payment -->
    <script src="{% static 'js/checkout.js' %}"></script>
    
    <!-- Stripe payments JS -->
    <script src="{% static 'js/jquery.payment.js' %}"></script>
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>

{% endblock %}

templates/order_status.html
{% extends 'base.html' %}

{% block page_title %}
    Order Status - 
{% endblock %}

{% block content %}

    <div class="container-fluid page-title text-center">
        Order Status
    </div> 

    {% if order %}
        <div class="container info-page-wrapper text-center">
            {% if order.status == 'Shipped' %}
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <span class="glyphicon glyphicon-send"></span>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 info-data">
                        Order was shipped {{ order.shipment_time }} via {{ order.shipment_method }}.<br/>
                        Tracking #{{ order.shipment_tracking }}
                    </div>
                </div>
            {% else %}
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <span class="glyphicon glyphicon-time"></span>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 info-data">
                        Order is being processed and prepared for shipment.
                    </div>
                </div>
            {% endif %}
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <span class="glyphicon glyphicon-ok"></span>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 info-data">
                    Order #{{ order.id }} was received {{ order.time }}
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <span class="glyphicon glyphicon-map-marker"></span>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 info-data">
                    {{ order.customer_name }}<br/>
                    {{ order.customer_street }}<br/>
                    {{ order.customer_city }}, {{order.customer_state }}<br/>
                    {{ order.customer_nation }} {{ order.customer_postal }}<br/>
                    {{ order.customer_email }}
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <span class="glyphicon glyphicon-shopping-cart"></span>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 info-data">
                    {% for item in order.orderitem_set.all %}
                        <p>
                            {{ item.product.name }}<br/>
                            {{ item.size }} - {{ item.width }} wide<br/>
                            {{ item.quantity }} @ ${{ item.price|floatformat:2 }}
                        </p>
                    {% endfor %}
                    <p>
                        Shipping: ${{ order.shipping_total|floatformat:2 }}<br/>
                        Order Total: ${{ order.order_total|floatformat:2 }}
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 info-data">
                    <a href="/order-status/">Search for a different order</a>
                </div>
            </div>
        </div>
    {% else %}

        <div class="container info-page-wrapper text-center">
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1 col-sm-12 col-sm-offset-0 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
                    Enter your order number and the zip/postal code from your shipping address to lookup your order. Don't have your info? Send us an e-mail at orders@uptownhoundboutique.com to get an update.
                </div>
            </div>
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4">
                    <form method="post" class="order-status-form">
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}
                        <div class="form-group text-left">
                            {{ form.invoice_number.label_tag }}
                            <div class="text-danger">{{ form.invoice_number.errors }}</div>
                            {{ form.invoice_number }}
                        </div>
                        <div class="form-group text-left">
                            {{ form.postal_code.label_tag }}
                            <div class="text-danger">{{ form.postal_code.errors }}</div>
                            {{ form.postal_code }}
                        </div>
                        <button type="submit" class="btn button-dark form-control">Lookup Order</button>
                    </form>
                </div>
            </div>
        </div>

    {% endif %}

{% endblock %}

templates/product.html
{% extends 'base.html' %}

{% block page_title %}
    {{ product.name }} - 
{% endblock %}

{% block content %}

    <div class="container-fluid page-title text-center">
        {{ product.name }}
    </div> 

    {% include 'includes/breadcrumbs.html' %}

    <div class="container">
        {% if cart_item %}
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 message-block">
                    {{ product.name }}: {{ cart_item.size }} added to your shopping bag.
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12 text-right">
                        <a class="image-popup" href="{{ product.main_img.image.url }}">
                            <img src="{{ product.main_img.image.url }}" class="img-responsive" id="js-main-image">
                        </a>
                    </div>
                </div>
                {% if product.prodimage_set.all.count > 1 %}
                    <div class="row">
                        {% for thumbnail in product.prodimage_set.all %}
                            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-3">
                                <img src="{{ thumbnail.image.url }}" class="img-responsive product-thumbnail">
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                {% if form.non_field_errors or form.variation.errors or form.quantity.errors %}
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 alert alert-danger text-danger text-right">
                            {{ form.non_field_errors }}
                            {{ form.variation.errors }}
                            {{ form.quantity.errors }}
                        </div>
                    </div>
                {% endif %}
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right product-price">{{ product.price_range }}</div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        {{ product.description|safe }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <form class="add-product-form" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="sr-only" for="{{ form.variation.id_for_label }}">Size</label>
                                {{ form.variation }}
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-xs-12 col-sm-3 col-md-2 col-lg-2">
                                        <label class="sr-only" for="{{ form.quantity.id_for_label }}">Quantity</label>
                                        {{ form.quantity }}
                                    </div>
                                    <div class="col-xs-12 col-sm-5 col-sm-offset-4 col-md-4 col-md-offset-6 col-lg-4 col-lg-offset-6 text-right">
                                        <button type="submit" class="btn btn-default form-control button-dark">Add to Bag</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center related-products">
                <span class="related-heading">Related Products</span>
            </div>
        </div>
        <div class="row">
            <div class="container">
                <div class="row">
                    {% for related_product in product.related_products.all %}
                        <div class="col-xs-6 col-sm-4 col-md-3 col-lg-3 product-thumb">
                            <a href="/product/{{ related_product.slug }}/">
                                <div class="row">
                                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                        <img src="{{ related_product.main_img.image.url }}" class="img-responsive">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-xs-11 col-xs-offset-1 col-sm-11 col-sm-offset-1 col-md-11 col-md-offset-1 col-lg-10 col-lg-offset-1 product-name">{{ related_product.name }}</div>
                                </div>
                                <div class="row">
                                    <div class="col-xs-11 col-xs-offset-1 col-sm-11 col-sm-offset-1 col-md-11 col-md-offset-1 col-lg-10 col-lg-offset-1 price">{{ related_product.price_range }}</div>
                                </div>
                            </a>
                        </div>
                        {% if forloop.counter|divisibleby:2 %}
                            <!-- Clear to fix wrapping row with uneven heights in mobile view -->
                            <div class="clearfix hidden-sm hidden-md hidden-lg"></div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}